name: tools.deps-builder

on: push
jobs:
  build:
    name: Build project
    runs-on: ubuntu-20.04
    container: clojure:tools-deps
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run stable tests
        run: clojure -M:test:runner -e:unstable
      - name: Run unstable tests
        run: clojure -M:test:runner -i:unstable
